title: "Portail pédagogique Technologie | TIM | Mathématiques"
description: "Cours de Technologie, TIM et Mathématiques"

url: "https://tifsec.github.io"
baseurl: ""

lang: fr
encoding: utf-8

markdown: kramdown

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
